"""empty message

Revision ID: 22f155d90acc
Revises: d41b719479c9
Create Date: 2023-01-24 17:42:50.331401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22f155d90acc'
down_revision = 'd41b719479c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'pricing_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('pricing_id', mysql.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
