"""empty message

Revision ID: d41b719479c9
Revises: dd584ef7ec58
Create Date: 2023-01-24 09:01:32.955394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd41b719479c9'
down_revision = 'dd584ef7ec58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(length=500), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('price', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('services', sa.Column('pricing_id', sa.String(length=300), nullable=True))
    op.drop_column('services', 'pricing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('pricing', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('services', 'pricing_id')
    op.drop_table('pricing')
    # ### end Alembic commands ###
