"""empty message

Revision ID: dd584ef7ec58
Revises: 27cefdbfe3e1
Create Date: 2023-01-24 08:57:26.329497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd584ef7ec58'
down_revision = '27cefdbfe3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('service', sa.String(length=500), nullable=True),
    sa.Column('contact_no', sa.String(length=300), nullable=True),
    sa.Column('booked_date', sa.String(length=300), nullable=True),
    sa.Column('is_confirm', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('image_p', sa.String(length=300), nullable=True),
    sa.Column('pricing', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('booked')
    # ### end Alembic commands ###
